/**
 *  Data : facebook pages 
 */

export default [
	'Oreo',
	'Chips ahoy Spain', 
	'KitKat Spain', 
	'Skittles', 
	'Naranjas Fontestad',
	'Kelloggs Poptarts', 
	'Ben and Jerrys Spain',
	'Reese’s',
	'ColaCao',
	'Mars',
	'M&M’s España',
	'Nutella',
	'Chocolates Valor',
	'Trident España',
	'Nestle bebe',
	'llaollao',
	'Ferrero Rocher'  , 
	'Milka',
	'Procter Gamble',
	'Naranjas España',
	'Galletas-Artesanas',
	'Recetas Thermomix',
	'Prigat Romania',
	'Heinz Soup UK',
	'Pringles',
	'Heinz Ketchup',
	'Orbit',
	'Nocilla',
	'Dippin Dots',
	'Comida Kraft',
	'Capullo',
	'Auntie Annes Pretzels',
	'Twix',
] as string[];
