export default  [
	'The best way to predict the future is to invent it',
	'If you can’t stop thinking about someone’s update, that’s called ‘status cling',
	'Accept who you are. Unless you’re a serial killer',
	'If you want something you never had before', 
	'you have to do something you’ve never done before',
	'Happiness can exist only in acceptance',
	'You can’t blame gravity for falling in love',
	'My formula for living is quite simple. I get up in the morning and I go to bed at night. In between, I occupy myself the best I can.',
	'I live in my own little world. But it’s ok, they know me here',
	'Let us be grateful to people who make us happy, they are the charming gardeners who make our souls blossom',
	'Always remember that you are absolutely unique. Just like everyone else.',
	'Not all those who wander are lost.',
	'Change your life today. Don’t gamble on the future, act now, without delay.',
	'Don’t promote negativity online and expect people to treat you with positivity in person.',
	'We love life, not because we are used to living but because we are used to loving.',
	'I am free of all prejudice. I hate everyone equally.',
	'We love life, not because we are used to living but because we are used to loving.',
	'It’s not what you look at that matters, it’s what you see.',
	'Before you marry a person, you should first make them use a computer with slow Internet to see who they really are.',
	'If you’re enjoying these quotes, you’ll love our collection of Will Ferrell quotes to give you a good laugh.',
	'A positive attitude gives you power over your circumstances instead of your circumstances having power over you.',
	'We know what we are, but know not what we may be.',
	'Just believe in yourself. Even if you don’t, pretend that you do and, at some point, you will.',
	'We can complain because rose bushes have thorns, or rejoice because rose bushes have thorns.',
	'The future belongs to those who believe in the beauty of their dreams.',
	'In three words I can sum up everything I’ve learned about life: it goes on.',
	'A single rose can be my garden … a single friend, my world.',
	'Focus on where you want to go, not on what you fear!',
	'If you’re enjoying these quotes, you’ll love our collection of Instagram Bio quotes that define the real you.',
	'Let us always meet each other with smile, for the smile is the beginning of love.',
	'Never let your failures get to your heart and never let your success get to your head.',
	'Either you run the day, or the day runs you.',
	'You can always tell when a man’s well informed. His views are pretty much like your own.',
	'You are genuinely happy if you don’t know why.',
	'Do not go where the path may lead, go instead where there is no path and leave a trail.',
	'I always feel like an idiot. But I am an idiot, so it kinda works out!',
	'Not how long, but how well you have lived is the main thing.',
	'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment',
	'To love and be loved is to feel the sun from both sides.',
	'If you genuinely want something, don’t wait for it teach yourself to be impatient.',
	'Nothing is impossible, the word itself says ‘I’m possible’!',
	'The best and most beautiful things in the world cannot be seen or even touched they must be felt with the heart.',
	'As you get older, three things happen. The first is your memory goes, and I can’t remember the other two.',
	'If opportunity doesn’t knock, build a door.',
	'The heart has reasons that reason does not understand.',
	'Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.',
	'I like long walks, especially when they are taken by people who annoy me.',
	'Everything will be okay in the end. If it’s not okay, then it’s not the end.',
	'Try to be a rainbow in someone’s cloud.',
	'Be yourself; everyone else is taken.',
	'What we achieve inwardly will change outer reality.',
	'Life shrinks or expands in proportion to one’s courage.',
	'Life is what happens while you are busy making other plans.',
	'Let your soul stand cool and composed before a million universes.',
	'What we need is more people who specialize in the impossible.',
	'Worry never robs tomorrow of its sorrow; it only saps today of its strength.',
	'Kindness is one thing you can’t give away. It always comes back.',
	'You’re never too broken to be fixed.',
	'If you have one true friend, you have more than your share.',
	'Dream as if you’ll live forever. Live as if you’ll die today.',
	'Life isn’t about finding yourself. Life is about creating yourself.',
	'I’m jealous of my parents. I’ll never have a kid as cool as theirs.',
	'Life is like riding a bicycle. To keep your balance, you must keep moving.',
	'People say nothing is impossible, but I do nothing every day.',
	'If opportunity doesn’t knock, build a door.',
	'There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.',
	'Life can only be understood backwards; but it must be lived forwards',
	'I’m a mirror. If you’re cool with me, I’m cool with you, and the exchange starts. What you see is what you reflect. If you don’t like what you see, then you’ve done something. If I’m standoffish, that’s because you are.'
] as string[];